sudo: required
language: generic

services:
  - docker

before_install:
- docker build -t bhanpurawalahaider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhanpurawalahaider/react-test npm test

after_success:
  - docker build -t bhanpurawalahaider/multi-client ./client
  - docker build -t bhanpurawalahaider/multi-nginx ./nginx
  - docker build -t bhanpurawalahaider/multi-server ./server
  - docker build -t bhanpurawalahaider/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push bhanpurawalahaider/multi-client
  - docker push bhanpurawalahaider/multi-nginx
  - docker push bhanpurawalahaider/multi-server
  - docker push bhanpurawalahaider/multi-worker

